name: detectron_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cpuonly=1.0
  - jupyter
  - opencv=3.4.2
  - pillow=8.0.1
  - pip=20.3
  - python=3.6
  - pytorch=1.7.1
  - torchaudio=0.7.2
  - torchvision=0.8.2
  - pip:
    - -r file:cpu_requirements.txt
